# COP3231 Lecture 12 & 13 Exercises

**Name**: Mertali

**ID**:    

# Building deep learning models with keras


## 1. Importing Data

In [10]:
import pandas as pd

In [34]:
df = pd.read_csv('/content/Data_Tables/hourly_wages.csv')
df

wage_per_hour  union  education_yrs  ...  south  manufacturing  construction
0             5.10      0              8  ...      0              1             0
1             4.95      0              9  ...      0              1             0
2             6.67      0             12  ...      0              1             0
3             4.00      0             12  ...      0              0             0
4             7.50      0             12  ...      0              0             0
..             ...    ...            ...  ...    ...            ...           ...
529          11.36      0             18  ...      0              0             0
530           6.10      0             12  ...      0              0             0
531          23.25      1             17  ...      0              0             0
532          19.88      1             12  ...      1              0             0
533          15.38      0             16  ...      0              1             0

[534 rows x 10 columns]

In [19]:
predictors = df.drop('wage_per_hour', axis = 1).values
target = df['wage_per_hour'].values

In [20]:
predictors

array([[ 0,  8, 21, ...,  0,  1,  0],
       [ 0,  9, 42, ...,  0,  1,  0],
       [ 0, 12,  1, ...,  0,  1,  0],
       ...,
       [ 1, 17, 25, ...,  0,  0,  0],
       [ 1, 12, 13, ...,  1,  0,  0],
       [ 0, 16, 33, ...,  0,  1,  0]])

In [44]:

predictors[1]

array([ 0,  9, 42, 57,  1,  1,  0,  1,  0])

## 2. Specifying a model

- Store the number of columns in the predictors data to n_cols. This has been done for you.
- Start by creating a Sequential model called model.
- Use the .add() method on model to add a Dense layer.
- Add 50 units, specify activation='relu', and the input_shape parameter to be the tuple (n_cols,) which means it has n_cols items in each row of data, and any number of rows of data are acceptable as inputs.
- Add another Dense layer. This should have 32 units and a 'relu' activation.
- Finally, add an output layer, which is a Dense layer with a single node. Don't use any activation function here.

In [39]:
# Import necessary modules
import keras
from keras.layers import Dense
from keras.models import Sequential

# Save the number of columns in predictors: n_cols
n_cols = predictors.shape[1]

# Set up the model: model
model = Sequential()

# Add the first layer
model.add(Dense(50, activation="relu",input_shape=(n_cols,)))

# Add the second layer
model.add(Dense(32, activation="relu"))

# Add the output layer
model.add(Dense(1))


## 3. Compiling the Model

- Compile the model using model.compile(). Your optimizer should be 'adam' and the loss should be 'mean_squared_error'.

In [42]:
# Compile the model
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Verify that model contains information from compiling
print("Loss function: " + model.loss)

Loss function: mean_squared_error


In [48]:
# Compile the model
model.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Verify that model contains information from compiling
print("Loss function: " + model.loss)

Loss function: mean_squared_error


## 4. Fitting the Model

- Fit the model. Remember that the first argument is the predictive features (predictors), and the data to be predicted (target) is the second argument.

In [46]:
# Fit the model
model.fit(predictors, target)

17/17 [==============================] - 0s 1ms/step - loss: 24.8319


In [49]:
# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Fit the model
model.fit(predictors,target)

17/17 [==============================] - 0s 1ms/step - loss: 27.5550


## 5. Single Prediction

- Create an array and make a single prediction with .predict() method.

In [50]:
df.columns

Index(['wage_per_hour', 'union', 'education_yrs', 'experience_yrs', 'age',
       'female', 'marr', 'south', 'manufacturing', 'construction'],
      dtype='object')

In [51]:
predictors[0]

array([ 0,  8, 21, 35,  1,  1,  0,  1,  0])

In [55]:
import numpy as np

prediction_array = np.array([[ 0,  6, 2,22, 1,  0,  0,  1,  1]])

In [61]:
x=(model.predict(prediction_array))[0]
(x*8*20)

array([1042.6194], dtype=float32)